# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42976e8600a55716a0dcf9d4e2f31ff7c0847fbc9b36d33dcb825cee4bdfce82d57d90a5df1cd4125c271cf8472288c380b054ca6f727f4fe241bd86f6f34997

test:
  secret_key_base: 4b42b5dd3b52da046bb9b569c4a8487808ae1a79e6dae49a58f11845cb644f6605db7cd430837ab4d31e959fdaeb8cf3f72f292c1e4837e221d4870af6e11aa7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
